name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/inventory-managment:latest
      
      - name: Build image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/myapp:latest \
            .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OVH_SSH_SECRET_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.OVH_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh ${{ secrets.OVH_SSH_USER }}@${{ secrets.OVH_SSH_HOST }} << 'EOF'
            cd /srv/inventory-managment
            docker compose pull
            docker compose up -d
            docker image prune -f
          EOF
