name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build image
        run: |
          docker build \
            -t ghcr.io/le-sourire-d-onja/inventory-managment:latest \
            .

      - name: Push image
        run: |
          docker push ghcr.io/le-sourire-d-onja/inventory-managment:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OVH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.OVH_SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_CLIENT_SECRET }}
    
      - name: Deploy
        run: |
          ssh ${{ secrets.OVH_SSH_USER }}@${{ secrets.OVH_SSH_HOST }} << EOF
      
            echo "${{ steps.app-token.outputs.token }}" | \
              docker login ghcr.io \
              -u x-access-token \
              --password-stdin
      
            cd /opt/app
            docker compose pull
            docker compose up -d
      
          EOF
